# Generated by Django 3.0.7 on 2020-06-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='enail',
            new_name='email',
        ),
    ]
